Python3 port
qvarforth/trackdirect pull request #25
Opened 2022-08-09 07:57 UTC by rhaamo

Things done (non exhaustive list):
- move python requirements to `requirements.txt` (including aprs-python)
- update docs for py3
- fix some `print()`
- references to python2 changed for python

The wsserver seems to run, however I am getting an issue with the collector part, which could be related to the singleton thing.

```
2022-08-09 09:54:09,465 - trackdirect - WARNING - Starting (Collecting from 127.0.0.1:10152 using NOCALL and -1)
2022-08-09 09:54:09,465 - trackdirect - ERROR - 'TrackDirectConfig' object has no attribute 'dbHostname'
Traceback (most recent call last):
  File "/home/dashie/dev/trackdirect/server/scripts/../bin/collector.py", line 59, in <module>
    trackDirectDataCollector = trackdirect.TrackDirectDataCollector(
  File "/home/dashie/dev/trackdirect/server/trackdirect/TrackDirectDataCollector.py", line 50, in __init__
    dbConnection = DatabaseConnection()
  File "/home/dashie/dev/trackdirect/server/trackdirect/database/DatabaseConnection.py", line 18, in __init__
    self.host = config.dbHostname
AttributeError: 'TrackDirectConfig' object has no attribute 'dbHostname'
```

2022-08-16 20:36 UTC, qvarforth commented
Thank you for your contribution!

I will look at the changes as soon as possible. I will probably set up a server to test them too. 

It may take some time before I have the opportunity to merge the changes as I have a lot to do in the near future. I apologize for that.

2022-08-17 07:00 UTC, rhaamo commented
Great thanks! No problem for the time to merge.

I've been running it on Python 3.8 and Nginx/PHP-FPM since 8 days now with one collector from my aprsc, and one collector from aprs-is global and so far no issue.

That make me thought that since I have renamed `trackdirect-python2.dockerfile` to `trackdirect-python.dockerfile` we will need peterus to update its docker build part for release images.

After this PR I will make somes with what I have worked with too:
- systemd services for collectors, wsserver, remover and ogn updater (both with timers)
- Nginx+PHP-FPM (90% working, I just have one non-working rewrite-rule for now)
- maybe some docs updates (virtualenv, rights, split in dedicated files, etc.)
 
Also if you are interested I can make a whole PR for [black](https://github.com/psf/black) and [flake8](https://flake8.pycqa.org/en/latest/) configs and fixes/code styling.

2022-09-11 10:41 UTC, peterus commented on server/scripts/collector.sh
>      cd $CURRENTDIR/..
can be deleted

2022-09-11 10:41 UTC, peterus commented on server/scripts/remover.sh
>      cd $CURRENTDIR/..
can be deleted

2022-09-11 10:41 UTC, peterus commented on server/scripts/stationremover.sh
>      cd $CURRENTDIR/..
can be deleted

2022-09-11 10:41 UTC, peterus commented on server/scripts/wsserver.sh
>      cd $CURRENTDIR/..
can be deleted

2022-09-11 10:41 UTC, peterus commented on trackdirect-python.dockerfile
> +  wget \
not used anymore. not sure about wget, will test and report.

2022-09-11 10:45 UTC, peterus commented
added some comments, will test the docker parts.

2022-09-12 08:11 UTC, peterus requested changes

2022-09-12 08:11 UTC, peterus commented on docker-compose-rel.yml
>        - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
please remove `heatmap` service as it is not used anymore

2022-09-12 08:11 UTC, peterus commented on trackdirect-python.dockerfile
> +  wget \
after testing, this is the correct apt-get call:

```
RUN apt-get update && apt-get install -y \
  python3 \
  python3-dev \
  python3-pip \
  python-is-python3 \
  git \
  && rm -rf /var/lib/apt/lists/*
```

2022-09-12 08:12 UTC, peterus commented
just finished my review. except the last changes I suggested, everything is working fine! thanks for this big changes!
@qvarforth go from my side ;)

2022-10-09 10:43 UTC, qvarforth commented
Thanks again for you for your contribution! I'm merging this now.

@peterus I can fix your suggested changes after it has been merged.

2022-10-09 10:44 UTC, merged